import { PrismaClient, CommissionType, ServicePriceType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Iniciando atualização completa de serviços com dados reais de mercado (2024/2025)...');

  const categories: Record<string, string> = {
    'Assistência Técnica': '',
    Informática: '',
    Smartphones: '',
    'Software & Desbloqueio': '',
    'Limpeza & Manutenção': '',
    'Instalação & Configuração': '',
  };

  // Lista consolidada com ~50 serviços reais
  const services = [
    // --- INFORMÁTICA ---
    {
      name: 'Diagnóstico Básico de Desktop',
      internalCode: 'SRV-0001',
      categoryId: categories['Informática'],
      priceBase: 60.00,
      estimatedTimeMin: 45,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Diagnóstico Básico de Notebook',
      internalCode: 'SRV-0002',
      categoryId: categories['Informática'],
      priceBase: 80.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Diagnóstico Avançado de Hardware (Laudo)',
      internalCode: 'SRV-0003',
      categoryId: categories['Informática'],
      priceBase: 120.00,
      estimatedTimeMin: 120,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Formatação de Desktop (s/ Backup)',
      internalCode: 'SRV-0004',
      categoryId: categories['Informática'],
      priceBase: 100.00,
      estimatedTimeMin: 90,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Formatação de Notebook (s/ Backup)',
      internalCode: 'SRV-0005',
      categoryId: categories['Informática'],
      priceBase: 120.00,
      estimatedTimeMin: 120,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Reinstalação de Windows com Drivers + Backup',
      internalCode: 'SRV-0006',
      categoryId: categories['Informática'],
      priceBase: 180.00,
      estimatedTimeMin: 180,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Instalação de Distribuição Linux',
      internalCode: 'SRV-0007',
      categoryId: categories['Informática'],
      priceBase: 100.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Limpeza de Vírus e Malware',
      internalCode: 'SRV-0008',
      categoryId: categories['Informática'],
      priceBase: 120.00,
      estimatedTimeMin: 90,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Otimização de Sistema (Software)',
      internalCode: 'SRV-0009',
      categoryId: categories['Informática'],
      priceBase: 80.00,
      estimatedTimeMin: 45,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Limpeza Interna Completa de Desktop',
      internalCode: 'SRV-0010',
      categoryId: categories['Informática'],
      priceBase: 100.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Limpeza Interna Completa de Notebook',
      internalCode: 'SRV-0011',
      categoryId: categories['Informática'],
      priceBase: 150.00,
      estimatedTimeMin: 90,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Troca de Pasta Térmica Desktop (Prata)',
      internalCode: 'SRV-0012',
      categoryId: categories['Informática'],
      priceBase: 80.00,
      estimatedTimeMin: 40,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Troca de Pasta Térmica Notebook (Prata)',
      internalCode: 'SRV-0013',
      categoryId: categories['Informática'],
      priceBase: 120.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Instalação de Memória RAM em Desktop',
      internalCode: 'SRV-0014',
      categoryId: categories['Informática'],
      priceBase: 50.00,
      estimatedTimeMin: 20,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Instalação de Memória RAM em Notebook',
      internalCode: 'SRV-0015',
      categoryId: categories['Informática'],
      priceBase: 70.00,
      estimatedTimeMin: 40,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Instalação de SSD com Clonagem de Sistema',
      internalCode: 'SRV-0016',
      categoryId: categories['Informática'],
      priceBase: 180.00,
      estimatedTimeMin: 120,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Instalação de Placa de Vídeo Dedicada',
      internalCode: 'SRV-0017',
      categoryId: categories['Informática'],
      priceBase: 80.00,
      estimatedTimeMin: 30,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Montagem de Kit Placa-Mãe/CPU/RAM',
      internalCode: 'SRV-0018',
      categoryId: categories['Informática'],
      priceBase: 150.00,
      estimatedTimeMin: 90,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Instalação e Configuração de Impressora',
      internalCode: 'SRV-0033',
      categoryId: categories['Informática'],
      priceBase: 80.00,
      estimatedTimeMin: 45,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
    },
    {
      name: 'Suporte Remoto (Hora Técnica)',
      internalCode: 'SRV-0034',
      categoryId: categories['Informática'],
      priceBase: 100.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      priceType: 'HOURLY',
    },
    {
      name: 'Atendimento Técnico Presencial (Hora)',
      internalCode: 'SRV-0035',
      categoryId: categories['Informática'],
      priceBase: 180.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      priceType: 'HOURLY',
    },
    {
      name: 'Recuperação de Dados em HD (Lógica)',
      internalCode: 'SRV-0036',
      categoryId: categories['Informática'],
      priceBase: 350.00,
      estimatedTimeMin: 240,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Configuração de Rede Wi-Fi',
      internalCode: 'SRV-0031',
      categoryId: categories['Informática'],
      priceBase: 120.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
    },
    {
      name: 'Configuração de Roteador Avançado',
      internalCode: 'SRV-0032',
      categoryId: categories['Informática'],
      priceBase: 180.00,
      estimatedTimeMin: 90,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
    },

    // --- SMARTPHONES ---
    {
      name: 'Troca de Tela (Display Incell/OLED)',
      internalCode: 'SRV-0019',
      categoryId: categories['Smartphones'],
      priceBase: 450.00, // Preço médio de serviço
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Troca de Bateria Premium',
      internalCode: 'SRV-0020',
      categoryId: categories['Smartphones'],
      priceBase: 180.00,
      estimatedTimeMin: 40,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Troca de Conector de Carga',
      internalCode: 'SRV-0021',
      categoryId: categories['Smartphones'],
      priceBase: 140.00,
      estimatedTimeMin: 50,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Reparo em Botão Power/Volume',
      internalCode: 'SRV-0022',
      categoryId: categories['Smartphones'],
      priceBase: 120.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Desoxidação de Placa (Banho Químico)',
      internalCode: 'SRV-0023',
      categoryId: categories['Smartphones'],
      priceBase: 180.00,
      estimatedTimeMin: 120,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },

    // --- VIDEOGAMES (ATUALIZADO) ---
    {
      name: 'Reparo de Drift no Analógico (PS4/PS5/Xbox)',
      internalCode: 'SRV-001',
      categoryId: categories['Assistência Técnica'],
      priceBase: 130.00, 
      estimatedTimeMin: 45,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Troca de Conector HDMI (PS4/PS5/Xbox One)',
      internalCode: 'SRV-002',
      categoryId: categories['Assistência Técnica'],
      priceBase: 280.00,
      estimatedTimeMin: 75,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Reballing de GPU/CPU (Processador)',
      internalCode: 'SRV-003',
      categoryId: categories['Assistência Técnica'],
      priceBase: 680.00,
      estimatedTimeMin: 180,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Reparo em Placa Mãe (Curto-Circuito)',
      internalCode: 'SRV-004',
      categoryId: categories['Assistência Técnica'],
      priceBase: 380.00,
      estimatedTimeMin: 120,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Troca de Unidade Óptica (Leitor)',
      internalCode: 'SRV-005',
      categoryId: categories['Assistência Técnica'],
      priceBase: 320.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Diagnóstico de Console de Videogame',
      internalCode: 'SRV-0024',
      categoryId: categories['Assistência Técnica'],
      priceBase: 80.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Reparo em Porta HDMI de Console',
      internalCode: 'SRV-0027',
      categoryId: categories['Assistência Técnica'],
      priceBase: 280.00, // Unificando preço
      estimatedTimeMin: 75,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Troca de HD por SSD em Console (500GB)',
      internalCode: 'SRV-0028',
      categoryId: categories['Assistência Técnica'],
      priceBase: 350.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Reparo de Drift Analógico (Controle)',
      internalCode: 'SRV-0029',
      categoryId: categories['Assistência Técnica'],
      priceBase: 80.00,
      estimatedTimeMin: 40,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Troca de Carcaça de Controle',
      internalCode: 'SRV-0030',
      categoryId: categories['Assistência Técnica'],
      priceBase: 120.00,
      estimatedTimeMin: 45,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Reballing de GPU/CPU (Geral)',
      internalCode: 'SRV-0037',
      categoryId: categories['Assistência Técnica'],
      priceBase: 650.00,
      estimatedTimeMin: 180,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },

    // --- LIMPEZA & MANUTENÇÃO (CONSOLES) ---
    {
      name: 'Limpeza Completa + Pasta Térmica High Performance',
      internalCode: 'SRV-010',
      categoryId: categories['Limpeza & Manutenção'],
      priceBase: 190.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Limpeza de Controle + Higienização',
      internalCode: 'SRV-011',
      categoryId: categories['Limpeza & Manutenção'],
      priceBase: 75.00,
      estimatedTimeMin: 30,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: false,
    },
    {
      name: 'Limpeza Interna de Console',
      internalCode: 'SRV-0025',
      categoryId: categories['Limpeza & Manutenção'],
      priceBase: 150.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Troca de Pasta Térmica de Console',
      internalCode: 'SRV-0026',
      categoryId: categories['Limpeza & Manutenção'],
      priceBase: 150.00, // Geralmente é o mesmo que limpeza completa
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },

    // --- SOFTWARE & DESBLOQUEIO ---
    {
      name: 'Desbloqueio / Custom Firmware (Switch/PS3)',
      internalCode: 'SRV-020',
      categoryId: categories['Software & Desbloqueio'],
      priceBase: 350.00,
      estimatedTimeMin: 120,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },
    {
      name: 'Instalação de SSD + Sistema + Backup',
      internalCode: 'SRV-021',
      categoryId: categories['Software & Desbloqueio'],
      priceBase: 160.00,
      estimatedTimeMin: 90,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
      requiresParts: true,
    },

    // --- INSTALAÇÃO & CONFIGURAÇÃO ---
    {
      name: 'Configuração Inicial + Update de Jogos',
      internalCode: 'SRV-030',
      categoryId: categories['Instalação & Configuração'],
      priceBase: 120.00,
      estimatedTimeMin: 60,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
      requiresDevice: true,
    },
    {
      name: 'Recuperação de Perfil / Conta Banida',
      internalCode: 'SRV-031',
      categoryId: categories['Instalação & Configuração'],
      priceBase: 90.00,
      estimatedTimeMin: 40,
      commissionType: 'PERCENT',
      commissionValue: 30.00,
    },
  ];

  for (const s of services) {
    const { categoryId: discardedCategoryId, ...serviceWithoutCategory } = s;
    void discardedCategoryId;
    const data = {
         ...serviceWithoutCategory,
         commissionType: s.commissionType as CommissionType,
         priceType: s.priceType as ServicePriceType | undefined,
     };
    await prisma.service.upsert({
      where: { internalCode: s.internalCode },
      update: data,
      create: data,
    });
  }

  console.log(`Banco de dados atualizado com sucesso! ${services.length} serviços processados.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
