export const ErrorCodes = {
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_MISSING_TOKEN: 'AUTH_REQUIRED',
  AUTH_UNAUTHORIZED: 'AUTH_REQUIRED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  AUTH_FORBIDDEN: 'ACCESS_DENIED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_MISSING_FIELD: 'VALIDATION_MISSING_FIELD',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

const STATUS_TO_CODE: Record<number, ErrorCode> = {
  400: ErrorCodes.VALIDATION_ERROR,
  401: ErrorCodes.AUTH_REQUIRED,
  403: ErrorCodes.ACCESS_DENIED,
  404: ErrorCodes.RESOURCE_NOT_FOUND,
  409: ErrorCodes.CONFLICT,
  429: ErrorCodes.RATE_LIMIT_EXCEEDED,
  500: ErrorCodes.INTERNAL_ERROR,
};

export function statusToCode(status: number): ErrorCode {
  // eslint-disable-next-line security/detect-object-injection
  return STATUS_TO_CODE[status] || ErrorCodes.INTERNAL_ERROR;
}
